DASHBOARD_UPDATES = 'dashboard-updates'
EVENT_TYPES_PER_HOUR_KEY = 'events:hourly:{event_type}:{hour}'
EVENT_TYPE_ALL_KEY = 'events:total:*'
EVENT_TYPE_KEY = 'events:total:{event_type}'
REDIS_URL = 'redis://localhost:6379'
TIME_FORMAT = '%Y-%m-%d-%H'
USER_ACTIVITY_ALL_KEY = 'user:activity:*'
USER_ACTIVITY_KEY = 'user:activity:{user_id}'
